import DefaultTags from "./DefaultTags";

export default function Head() {
  return (
    <>
      <DefaultTags />
      <title>Vértice | MAT</title>
      <meta name="description" content="Generated by create next app" />
    </>
  )
}
